spring:
    datasource:
        url: jdbc:mysql://localhost:3306/blogdb
        username: username
        password: password
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
