spring:
  application:
    name: notary_admin_server

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/notary_db}
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

security:
  public-endpoints: ${PUBLIC_ENDPOINTS:}

jwt:
  signerKey: ${JWT_SIGNER_KEY}
  issuer: ${JWT_ISSUER:}
  valid-duration: ${JWT_VALID_DURATION:}
  refreshable-duration: ${JWT_REFRESHABLE_DURATION:}

app:
  seed:
    enabled: ${SEED_ENABLED:false}
    admin:
      password: ${SEED_ADMIN_PASSWORD:}
      email: ${SEED_ADMIN_EMAIL:}
      full-name: ${SEED_ADMIN_FULL_NAME:}
      phone-number: ${SEED_ADMIN_PHONE_NUMBER:}
      address: ${SEED_ADMIN_ADDRESS:}
      dob: ${SEED_ADMIN_DOB:}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1
