spring:
  application:
    name: notary_admin_server

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/notary_db}
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

security:
  public-endpoints: ${PUBLIC_ENDPOINTS:/oauth2/**,/auth/**,/api/v1/auth/**}

jwt:
  signerKey: ${JWT_SIGNER_KEY}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1
